// ret: array con todos los tipos de criaturas

var res;
res[0] = m_esp_paloma;
res[1] = m_esp_mosca;
res[2] = m_esp_buho;
res[3] = m_esp_escarabajo;
res[4] = m_esp_abeja;
res[5] = m_esp_pollo;
res[6] = m_esp_meduza;
res[7] = m_esp_zancudo;
res[8] = m_esp_aguila;
res[9] = m_esp_buitre;
res[10] = m_esp_libelula;
res[11] = m_esp_loro;
res[12] = m_esp_salmon;
res[13] = m_esp_atun;
res[14] = m_esp_tiburon;
res[15] = m_esp_ballena;
res[16] = m_esp_gusano;
res[17] = m_esp_aranna;
res[18] = m_esp_caracol;
res[19] = m_esp_plancton;
res[20] = m_esp_alacran;
res[21] = m_esp_hormiga;
res[22] = m_esp_rana;
res[23] = m_esp_lagarto;
res[24] = m_esp_raton;
res[25] = m_esp_cabra;
res[26] = m_esp_toro;
res[27] = m_esp_pinguino;
res[28] = m_esp_conejo;
res[29] = m_esp_avestruz;
res[30] = m_esp_mico;
res[31] = m_esp_vampiro;
res[32] = m_esp_golem;
res[33] = m_esp_perro;
res[34] = m_esp_polar;
res[35] = m_esp_oso;
res[36] = m_esp_tigre;
return res;
